apiVersion: v1
kind: Secret
metadata:
  name: {{ include "althea-backend.fullname" . }}
  labels:
    {{- include "althea-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secret.APP_SECRET | quote }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  JWT_PASSPHRASE: {{ .Values.secret.JWT_PASSPHRASE | quote }}
  MAILER_DSN: {{ .Values.secret.MAILER_DSN | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secret.STRIPE_SECRET_KEY | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secret.STRIPE_WEBHOOK_SECRET | quote }}
  {{- if .Values.jwt.privateKey }}
  JWT_PRIVATE_KEY: {{ .Values.jwt.privateKey | quote }}
  JWT_PUBLIC_KEY: {{ .Values.jwt.publicKey | quote }}
  {{- end }}
