apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "althea-frontend.fullname" . }}
  labels:
    {{- include "althea-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "althea-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "althea-frontend.selectorLabels" . | nindent 8 }}
      annotations:
        # Force redéploiement si apiUrl change
        checksum/apiUrl: {{ .Values.apiUrl | sha256sum }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
